name: Tests on PR

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr-no-codecov-no-headless.yml@v0
